# Configuration des tâches CrewAI pour l'amélioration des bandes dessinées
# Basé sur les meilleures pratiques de la documentation CrewAI

storytelling_task:
  description: >
    Analyse et améliore la structure narrative du scénario de bande dessinée original.
    
    Tu dois améliorer:
    1. La cohérence narrative entre les scènes
    2. La progression dramatique et le rythme
    3. La caractérisation des personnages
    4. L'adaptation au public cible ({target_audience})
    5. La qualité des descriptions visuelles pour chaque scène
    
    Contexte du projet:
    - Prompt utilisateur: "{user_prompt}"
    - Style demandé: "{style}"
    - Scénario original: {original_scenario}
    
    Garde le même nombre de scènes mais améliore leur description et leur enchaînement.
    Assure-toi que chaque scène a une description visuelle claire et précise.
  expected_output: >
    Un scénario amélioré au format JSON avec:
    - title: titre amélioré et accrocheur
    - scenes: liste des scènes avec descriptions visuelles enrichies
    - narrative_improvements: liste des améliorations apportées à la narration
    Formaté en JSON valide sans marqueurs de code.
  agent: storyteller_agent

dialogue_optimization_task:
  description: >
    Optimise tous les dialogues du scénario amélioré pour qu'ils soient naturels et adaptés aux bulles BD.
    
    Pour chaque dialogue, assure-toi qu'il soit:
    1. Naturel et authentique pour le personnage
    2. Adapté au langage du public cible
    3. Respectueux des contraintes de bulles BD (max 40 caractères par ligne, max 3 lignes)
    4. Exempt de répétitions et de formulations artificielles
    5. Varié dans le style selon les personnages et situations
    6. Expressif et impactant
    
    Types de dialogues à considérer:
    - Parole normale
    - Cri ou exclamation
    - Chuchotement
    - Pensée intérieure
    
    Crée des dialogues qui sonnent vrais et qui s'intègrent parfaitement dans des bulles de BD.
  expected_output: >
    Le scénario avec dialogues optimisés au format JSON contenant:
    - Chaque dialogue respectant les contraintes de bulle BD
    - Dialogues naturels et expressifs
    - Variations appropriées selon les personnages
    - dialogue_improvements: explications des améliorations apportées
    Formaté en JSON valide sans marqueurs de code.
  agent: dialogue_agent
  context: [storytelling_task]

layout_optimization_task:
  description: >
    Optimise le placement et la forme des bulles de dialogue pour chaque scène.
    
    Pour chaque scène, détermine:
    1. La position optimale de chaque bulle selon la description de scène
    2. Comment éviter que les bulles cachent des éléments importants
    3. L'ordre de lecture optimal (gauche→droite, haut→bas)
    4. Le type de bulle approprié (normale, pensée, cri, chuchotement)
    5. Les dimensions optimales selon le texte
    6. La position des personnages pour guider le placement des bulles
    
    Règles de layout BD:
    - Bulles de parole normale: forme ovale avec queue pointue
    - Bulles de pensée: forme nuage avec petites bulles
    - Bulles de cri: contour dentelé
    - Bulles de chuchotement: contour pointillé
    
    Ajoute des métadonnées précises de placement pour chaque bulle.
  expected_output: >
    Le scénario final avec métadonnées de layout au format JSON contenant:
    - Positions optimales des bulles (coordonnées relatives)
    - Types de bulles pour chaque dialogue
    - Ordre de lecture pour chaque scène
    - layout_metadata: informations techniques détaillées pour le rendu
    - character_positions: positions estimées des personnages
    Formaté en JSON valide sans marqueurs de code.
  agent: layout_agent
  context: [storytelling_task, dialogue_optimization_task]

final_review_task:
  description: >
    Effectue une révision complète et finale du scénario amélioré.
    
    Vérifie minutieusement:
    1. Cohérence narrative globale de l'histoire
    2. Qualité et naturel de tous les dialogues
    3. Efficacité du layout proposé pour chaque scène
    4. Respect du brief original et du public cible
    5. Qualité professionnelle générale
    6. Adaptation au style demandé
    7. Lisibilité et fluidité de lecture
    
    Si tu détectes des problèmes, propose des corrections finales.
    Assure-toi que le résultat final est prêt pour la production.
  expected_output: >
    Le scénario final validé et optimisé au format JSON avec:
    - Toutes les améliorations intégrées et validées
    - Une note de qualité globale (sur 10)
    - review_notes: commentaires détaillés sur les améliorations apportées
    - final_recommendations: suggestions pour le rendu visuel
    - quality_score: évaluation de la qualité finale
    - ready_for_production: boolean indiquant si c'est prêt
    Formaté en JSON valide sans marqueurs de code.
  agent: reviewer_agent
  context: [storytelling_task, dialogue_optimization_task, layout_optimization_task]
  output_file: enhanced_comic_scenario.json
